src/AppBundle/Entity/Fulfillment.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Table(name="fulfillment")
 * @ORM\Entity()
 */
class Fulfillment
{

    public const TYPE_IN_PROGRESS = 0;
    public const TYPE_DONE = 1;
    public const TYPE_FAILURE = 2;

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\User")
     */
    protected $user;

    /**
     * @var int
     * @ORM\Column(name="`type`", type="integer", nullable=false)
     */
    protected $type;

    /**
     * @var string
     * @ORM\Column(name="context", type="text", nullable=true)
     */
    protected $context;

    /**
     * @var int
     * @ORM\Column(name="order_number", type="bigint")
     * @Assert\NotBlank()
     * @Assert\Range(min="1000", max="99999999999")
     */
    protected $order;

    /**
     * @var string
     * @ORM\Column(type="string", length=64)
     * @Assert\NotBlank()
     */
    protected $trackingNumber;

    /**
     * @var string
     * @ORM\Column(type="string", length=512, nullable=true)
     * @Assert\Url()
     */
    protected $trackingLink;

    /**
     * @var string
     * @ORM\Column(type="string", nullable=true)
     */
    protected $shipperName;

    /**
     * @var string
     * @ORM\Column(type="string", nullable=true)
     */
    protected $supplier;

    /**
     * @return string
     */
    public function getTrackingNumber(): string
    {
        return $this->trackingNumber;
    }

    /**
     * @param string $trackingNumber
     *
     * @return Fulfillment
     */
    public function setTrackingNumber(?string $trackingNumber): Fulfillment
    {
        $this->trackingNumber = $trackingNumber;

        return $this;
    }

    /**
     * @param mixed $id
     *
     * @return Fulfillment
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * @param User $user
     *
     * @return Fulfillment
     */
    public function setUser(User $user): Fulfillment
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @param int $type
     *
     * @return Fulfillment
     */
    public function setType(?int $type): Fulfillment
    {
        $this->type = $type;

        return $this;
    }

    /**
     * @param string $context
     *
     * @return Fulfillment
     */
    public function setContext(string $context): Fulfillment
    {
        $this->context = $context;

        return $this;
    }

    /**
     * @param int $order
     *
     * @return Fulfillment
     */
    public function setOrder(?int $order): Fulfillment
    {
        $this->order = $order;

        return $this;
    }

    /**
     * @param string $trackingLink
     *
     * @return Fulfillment
     */
    public function setTrackingLink(?string $trackingLink): Fulfillment
    {
        $this->trackingLink = $trackingLink;

        return $this;
    }

    /**
     * @param string $shipperName
     *
     * @return Fulfillment
     */
    public function setShipperName(?string $shipperName): Fulfillment
    {
        $this->shipperName = $shipperName;

        return $this;
    }

    /**
     * @param string $supplier
     *
     * @return Fulfillment
     */
    public function setSupplier(?string $supplier): Fulfillment
    {
        $this->supplier = $supplier;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return User
     */
    public function getUser(): User
    {
        return $this->user;
    }

    /**
     * @return int
     */
    public function getType(): int
    {
        return $this->type;
    }

    /**
     * @return string
     */
    public function getContext(): string
    {
        return $this->context ?? '';
    }

    /**
     * @return array
     */
    public function getDecodedContext(): array
    {
        return json_decode($this->context ?? '[]', true);
    }

    /**
     * @return int
     */
    public function getOrder(): ?int
    {
        return $this->order;
    }

    /**
     * @return string
     */
    public function getTrackingLink(): string
    {
        return $this->trackingLink ?? '';
    }

    /**
     * @return string
     */
    public function getShipperName(): string
    {
        return $this->shipperName ?? '';
    }

    /**
     * @return string
     */
    public function getSupplier(): string
    {
        return $this->supplier ?? '';
    }

    public function isDone(): bool
    {
        return $this->type === self::TYPE_DONE;
    }

    public function isInProgress(): bool
    {
        return $this->type === self::TYPE_IN_PROGRESS;
    }

    public function isFailed(): bool
    {
        return $this->type === self::TYPE_FAILURE;
    }

}

src/AppBundle/Form/FulfillmentForm.php
<?php

namespace AppBundle\Form;

use AppBundle\Entity\Fulfillment;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FulfillmentForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('order', NumberType::class, [
                'label' => 'fulfillment.form.order',
                'attr' => [
                    'min' => 1,
                ]
            ])
            ->add('trackingNumber', TextType::class, [
                'label' => 'fulfillment.form.tracking-number',
            ])
            ->add('trackingLink', TextType::class, [
                'label' => 'fulfillment.form.tracking-link',
                'required' => false,
            ])
            ->add('shipperName', TextType::class, [
                'label' => 'fulfillment.form.shipper-name',
                'required' => false,
            ])
            ->add('supplier', TextType::class, [
                'label' => 'fulfillment.form.supplier',
                'required' => false,
            ])
            ->add('submit', SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Fulfillment::class,
        ]);
    }
}

src/AppBundle/Controller/FulfillmentController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Fulfillment;
use AppBundle\Entity\User;
use AppBundle\Form\FulfillmentForm;
use Doctrine\Common\Persistence\ManagerRegistry;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\User\UserInterface;

class FulfillmentController extends Controller
{
    /**
     * @param Request $request
     * @param User $user
     *
     * @return RedirectResponse
     *
     * @Route("/fulfillment", name="app_fulfillment")
     * @Method("GET")
     */
    public function indexAction(UserInterface $user): Response
    {
        $fulfillments = $this->getDoctrine()->getManager()->getRepository(Fulfillment::class)->findBy([
            'user' => $user
        ]);

        return $this->render('AppBundle:Fulfillment:index.html.twig', [
            'user' => $user,
            'fulfillments' => $fulfillments
        ]);
    }

    /**
     * @Route("/fulfillment/{id}", name="fulfillment_show")
     * @Method("GET")
     */
    public function showAction(UserInterface $user, Fulfillment $fulfillment)
    {
        if ($fulfillment->getUser()->getId() !== $user->getId()) {
            return $this->createAccessDeniedException();
        }

        return $this->render('AppBundle:Fulfillment:show.html.twig', [
            'user' => $user,
            'fulfillment' => $fulfillment
        ]);
    }

    /**
     * @Route("/fulfillment/delete/{id}", name="fulfillment_delete")
     * @Method("GET")
     */
    public function deleteAction(UserInterface $user, Fulfillment $fulfillment)
    {
        if ($fulfillment->getUser()->getId() !== $user->getId()) {
            return $this->createAccessDeniedException();
        }

        $em = $this->getDoctrine()->getManager();
        $em->remove($fulfillment);
        $em->flush($fulfillment);

        return $this->redirectToRoute('app_fulfillment');
    }

    /**
     * @Route("/fulfillment/edit/{id}", name="fulfillment_edit")
     * @Method("GET")
     */
    public function editAction(UserInterface $user, Fulfillment $fulfillment)
    {
        if ($fulfillment->getUser()->getId() !== $user->getId()) {
            return $this->createAccessDeniedException();
        }

        return $this->render('AppBundle:Fulfillment:edit.html.twig', [
            'user' => $user,
            'fulfillment' => $fulfillment,
            'form' => $this->getForm($fulfillment)->createView()
        ]);
    }

    private function getForm(Fulfillment $fulfillment)
    {
        return $this->createForm(FulfillmentForm::class, $fulfillment, [
            'action' => $this->generateUrl('fulfillment_edit', ['id' => $fulfillment->getId()]),
            'method' => 'POST',
        ]);
    }

    /**
     * @Route("/fulfillment/edit/{id}")
     * @Method("POST")
     */
    public function updateAction(
        UserInterface $user,
        Fulfillment $fulfillment,
        Request $request,
        ManagerRegistry $doctrine
    ) {
        if ($fulfillment->getUser()->getId() !== $user->getId()) {
            return $this->createAccessDeniedException();
        }

        $form = $this->getForm($fulfillment);
        if (!$form->handleRequest($request)->isSubmitted() || !$form->isValid()) {
            return $this->render('AppBundle:Fulfillment:edit.html.twig', [
                'user' => $user,
                'fulfillment' => $fulfillment,
                'form' => $form->createView()
            ]);
        }

        $doctrine->getManager()->flush($fulfillment);
        $fulfillment->setType(Fulfillment::TYPE_IN_PROGRESS);
        $request->getSession()->getFlashBag()->add('success', 'fulfillment.flash.edited');
        $this->get('old_sound_rabbit_mq.fulfillment_producer')->publish($fulfillment->getId());

        return $this->redirectToRoute('app_fulfillment');
    }
}

src/AppBundle/Resources/views/Fulfillment/edit.html.twig
{% extends '::base.html.twig' %}

{% block content %}
    <div class="toc-block">
        <section>
            <div class="column">
                <article>
                    <div class="card columns twelve">
                        <h2>{{ 'fulfillment.form.edit' | trans }}</h2>
                        {{ form_start(form) }}
                            {{ form_row(form.order) }}
                            {{ form_row(form.trackingNumber) }}
                            {{ form_row(form.trackingLink) }}
                            {{ form_row(form.shipperName) }}
                            {{ form_row(form.supplier) }}
                            {{ form_row(form.submit) }}
                        {{ form_end(form) }}
                    </div>
                </article>
            </div>
        </section>
    </div>
{% endblock %}

src/AppBundle/Resources/views/Fulfillment/index.html.twig
{% extends '::base.html.twig' %}

{% block content %}
    <div class="toc-block">
        <section>
            <div class="column">
                <article>
                    <div class="card columns twelve">
                        <table>
                            <thead>
                            <tr>
                                <th>{{ 'fulfillment.list.header.order' | trans}}</th>
                                <th>{{ 'fulfillment.list.header.tracking' | trans}}</th>
                                <th>{{ 'fulfillment.list.header.shipper' | trans}}</th>
                                <th>{{ 'fulfillment.list.header.supplier' | trans}}</th>
                                <th>{{ 'fulfillment.list.header.status' | trans}}</th>
                                <th>{{ 'fulfillment.list.header.details' | trans}}</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for fulfillment in fulfillments %}
                                <tr>
                                    <td><a href="/admin/orders/{{ fulfillment.order }}" target="_parent">#{{ fulfillment.order }}</a>
                                    <td>
                                        {% if fulfillment.trackingLink is not empty %}
                                            <a href="{{ fulfillment.trackingLink }}" target="_blank">
                                                {{ fulfillment.trackingNumber }}
                                                &nbsp; <sup><i class="icon-offsite"></i></sup>
                                            </a>
                                        {% else %}
                                            {{ fulfillment.trackingNumber }}
                                        {% endif %}
                                    </td>
                                    <td>{{ fulfillment.shipperName | default('-') }}</td>
                                    <td>{{ fulfillment.supplier | default('-') }}</td>
                                    <td>
                                        {% if fulfillment.done %}<span class="tag green">{{ 'status.done' | trans }}</span>
                                        {% elseif fulfillment.failed %}<span class="tag red">{{ 'status.failure' | trans }}</span>
                                        {% elseif fulfillment.inProgress %}<span class="tag blue">{{ 'status.in_progress' | trans }}</span>
                                        {% endif %}
                                    </td>
                                    <td><a href="{{ path('fulfillment_show', {'id': fulfillment.id}) }}">Details</a></td>
                                </tr>
                            {% else %}
                                <tr>
                                    <td colspan="5" class="align-center">{{ 'fulfillment.list.empty' | trans }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>

                    </div>
                </article>
            </div>
        </section>
    </div>
{% endblock %}

src/AppBundle/Resources/views/Fulfillment/macro.html.twig
{% macro array_to_list(array) %}
    {% from _self import array_to_list %}
    {% for key, value in array %}
        <ul>
            <li>
                {% set number = key matches '/^\\d+$/' %}
                {% if not number %}{{ key }}: {% endif %}
                {% if value is iterable %}
                    {{ array_to_list(value) }}
                {% else %}{{ value }}
                {% endif %}
            </li>
        </ul>
    {% endfor %}
{% endmacro %}

src/AppBundle/Resources/views/Fulfillment/show.html.twig
{% extends '::base.html.twig' %}

{% import '@App/Fulfillment/macro.html.twig' as macro %}

{% block content %}
    <div class="toc-block">
        <section>
            <div class="column">
                <article>
                    <div class="column twelve card align-right transparent">
                        <a onclick="return confirm('{{ 'fulfillment.delete-confirm' | trans | e('js') }}')" href="{{ path('fulfillment_delete', {'id': fulfillment.id}) }}" class="button warning">{{ 'fulfillment.delete' | trans }}</a>
                        {% if fulfillment.failed %}
                            <a href="{{ path('fulfillment_edit', {'id': fulfillment.id}) }}" class="button">{{ 'fulfillment.edit' | trans }}</a>
                        {% else %}
                            <a href="#" class="button disabled">{{ 'fulfillment.edit' | trans }}</a>
                        {% endif %}
                    </div>
                </article>
                <article>
                    <div class="card columns twelve">
                        <table>
                            <thead>
                            <tr>
                                <th>{{ 'fulfillment.list.header.order' | trans }}</th>
                                <th>{{ 'fulfillment.list.header.tracking' | trans }}</th>
                                <th>{{ 'fulfillment.list.header.shipper' | trans }}</th>
                                <th>{{ 'fulfillment.list.header.supplier' | trans }}</th>
                                <th>{{ 'fulfillment.list.header.status' | trans }}</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td><a href="/admin/orders/{{ fulfillment.order }}" target="_parent">#{{ fulfillment.order }}</a></td>
                                <td>
                                    {% if fulfillment.trackingLink is not empty %}
                                        <a href="{{ fulfillment.trackingLink }}" target="_blank">
                                            {{ fulfillment.trackingNumber }}
                                            &nbsp; <sup><i class="icon-offsite"></i></sup>
                                        </a>
                                    {% else %}
                                        {{ fulfillment.trackingNumber }}
                                    {% endif %}
                                </td>
                                <td>{{ fulfillment.shipperName | default('-') }}</td>
                                <td>{{ fulfillment.supplier | default('-') }}</td>
                                <td>
                                    {% if fulfillment.done %}<span class="tag green">{{ 'status.done' | trans }}</span>
                                    {% elseif fulfillment.failed %}<span
                                            class="tag red">{{ 'status.failure' | trans }}</span>
                                    {% elseif fulfillment.inProgress %}<span
                                            class="tag blue">{{ 'status.in_progress' | trans }}</span>
                                    {% endif %}
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </article>
                {% if fulfillment.failed %}
                    <article>
                        <div class="card columns twelve">
                            <h2>{{ 'fulfillment.detail.error.title' | trans }}</h2>
                            {{ macro.array_to_list(fulfillment.decodedContext) }}
                        </div>
                    </article>
                {% endif %}
            </div>
        </section>
    </div>
{% endblock %}